//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginenregistratieProjectC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gebruiker
    {
        public int GebruikerID { get; set; }
        public string Voornaam { get; set; }
        public string Achternaam { get; set; }
        public string Emailadres { get; set; }
        public string Wachtwoord { get; set; }
        public bool IsEmailGeverifieerd { get; set; }
        public System.Guid ActivatieCode { get; set; }
        public string Klas { get; set; }
        public string Rol { get; set; }
        public string ResetWachtwoordCode { get; set; }
    }
}
